site_name: Deep Groundwater
site_description: A collection of open-source blog posts and articles
site_url: https://deepgroundwater.com
repo_url: https://github.com/deepgroundwater/deepgroundwater.github.io
repo_name: deepgroundwater/DeepGroundwater.github.io

theme:
  name: material
  features:
    - navigation.instant
  icon:
    repo: fontawesome/brands/git-alt

plugins:
  - search
  - blog

nav:
  - Home: index.md
  - Blog:
     - blog/index.md
