authors:
  taddyb:
    name: Tadd Bindas
    description: Board Member
    avatar: https://github.com/taddyb.png
    url: https://github.com/taddyb
  jmframe:
    name: Jonathan Frame
    description: Board Member
    avatar: https://github.com/jmframe.png
    url: https://github.com/jmframe
  rappjer1:
    name: Jeremy Rapp
    description: Board Member
    avatar: https://github.com/rappjer1.png
  RY4GIT:
    name: Ryoko Araki
    description: Board Member
    avatar: https://github.com/RY4GIT.png
    url: https://github.com/RY4GIT
  soelemaafnan:
    name: Soelem Aafnan Bhuiyan
    description: Board Member
    avatar: https://github.com/soelemaafnan.png
