authors:
  taddyb:
    name: Tadd Bindas
    description: Creator
    avatar: https://github.com/taddyb.png
  jmframe:
    name: Jonathan M. Frame
    description: Contributor
    avatar: https://avatars.githubusercontent.com/u/44035137?s=40&v=4