authors:
  taddyb:
    name: Tadd Bindas
    description: Board Member
    avatar: https://github.com/taddyb.png
  jmframe:
    name: Jonathan Frame
    description: Board Member
    avatar: https://avatars.githubusercontent.com/u/44035137?s=40&v=4
  rappjer1:
    name: Jeremy Rapp
    description: Board Member
    avatar: https://github.com/rappjer1.png
  RY4GIT:
    name: Ryoko Araki
    description: Board Member
    avatar: https://github.com/RY4GIT.png
  soelemaafnan:
    name: Soelem Aafnan Bhuiyan
    description: Board Member
    avatar: https://github.com/soelemaafnan.png
