authors:
  taddyb:
    name: Tadd Bindas
    description: Editoral Board Member
    avatar: https://github.com/taddyb.png
  jmframe:
    name: Jonathan Frame
    description: Editoral Board Member
    avatar: https://github.com/jmframe.png
  rappjer1:
    name: Jeremy Rapp
    description: Editoral Board Member
    avatar: https://github.com/rappjer1.png
  RY4GIT:
    name: Ryoko Araki
    description: Editoral Board Member
    avatar: https://github.com/RY4GIT.png
  soelemaafnan:
    name: Soelem Aafnan Bhuiyan
    description: Editoral Board Member
    avatar: https://github.com/soelemaafnan.png
